### ISSUE TITLE
You need to ignore some files

### ISSUE THREAD

**Issue by deavisdude** [bklooster/GGJ2015#1]
Using git with unity needs to have some files ignored to function properly.  I noticed some code in your repo that is supposed to be ignored.  For instance, one user changed a windows path to the unity editor to a mac path...

Here is what you need ignored:
# =============== #
# Unity generated #
# =============== #
Temp/
Library/

# ===================================== #
# Visual Studio / MonoDevelop generated #
# ===================================== #
ExportedObj/
obj/
*.svd
*.userprefs
/*.csproj
*.pidb
*.suo
/*.sln
*.user
*.unityproj
*.booproj

# ============ #
# OS generated #
# ============ #
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

**Comment by deavisdude** [comment]
the bolded things are actually between pound signs (hashtags), github thinks I meant to bold them, but they are just from the .gitignore

**Comment by bklooster** [comment]
Thanks, updated.
